base_url = "/"
compile_sass = true
build_search_index = true

theme = "anemone"

taxonomies = [{ name = "tags" }]

[markdown]
highlight_code = true

[extra]
twitter_card = true
twitter_title = "/autoparallel/"
twitter_url = "https://autoparallel.xyz"
twitter_description = ">>> going with the flow >>>"
twitter_image = "/images/borromean_rings.png"
header_nav = [
    { url = "/", name_en = "/home/" },
    { url = "/braindump", name_en = "/braindump/" },
    { url = "/blog", name_en = "/blog/" },
]
