services:
    zola: 
        build:
            context: .
            target: zola
        command: serve --interface 0.0.0.0
        volumes:
            - .:/project
        ports:
            - '1111:1111'