# On every push this script is executed
on: push
name: Build and deploy GH Pages
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: Update submodules
        run: |
          git submodule update --init --recursive
      - name: Check themes/anemone/templates directory
        run: |
          ls themes/anemone/
      - name: Build and Deploy
        uses: shalzz/zola-deploy-action@v0.17.2
        env:
          PAGES_BRANCH: main
          TOKEN: ${{ secrets.TOKEN }}